# 1. Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-backend
  template:
    metadata:
      labels:
        app: board-backend
    spec:
      containers:
        - name: board-backend
          image: cheongmyeong/board-app:latest
          ports:
            - containerPort: 8080
---
# 2. Backend Service
apiVersion: v1
kind: Service
metadata:
  name: board-app-service
spec:
  type: ClusterIP # 프론트엔드만 백엔드에 접근하면 되므로 내부용으로 설정
  selector:
    app: board-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# 3. Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-frontend
  template:
    metadata:
      labels:
        app: board-frontend
    spec:
      containers:
        - name: board-frontend
          image: cheongmyeong/board-frontend:latest
          ports:
            - containerPort: 80
---
# 4. Frontend Service (사용자가 접속하는 대문)
apiVersion: v1
kind: Service
metadata:
  name: board-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: board-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80