spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: board_user
    password: board_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

storage:
  s3:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
    bucket: board-attachment
    region: us-east-1

security:
  jwt:
    secret: "CHANGE_ME_TO_LONG_RANDOM_SECRET_32+_CHARS"
    access-token-exp-minutes: 60