name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Java and Node CI with Docker"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/persistence.yaml
          kubectl apply -f k8s/backend-config.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl rollout restart deployment/board-backend
          kubectl rollout restart deployment/board-frontend

#    # 욕설 필터링 서비스 cloud run에 배포
#      - name: Deploy Profanity Filter to Cloud Run
#        id: deploy-filter
#        uses: 'google-github-actions/deploy-cloudrun@v1'
#        with:
#          service: 'profanity-filter'
#          image: '${{ secrets.DOCKER_USERNAME }}/profanity-filter:latest'
#          region: 'asia-northeast3' # 서울 리전
#          flags: '--no-allow-unauthenticated' # 인증된 요청만 허용
#
#      # 배포된 Cloud Run의 URL을 확인하기 위한 로그 (선택사항)
#      - name: Show Filter Service URL
#        run: echo "Filter Service URL is ${{ steps.deploy-filter.outputs.url }}"
#
#
#
